spring.mvc.view.prefix = /WEB-INF/views/
spring.mvc.view.suffix = .jsp
server.servlet.context-path=/transgatepayapi


server.error.path=/error

#server.error.whitelabel.enabled=false
server.error.include-stacktrace=always

server.port=82
#server.ssl.enabled=true
#server.ssl.key-store: src/main/resources/paycotransgateapi.p12
#server.ssl.key-store-password: Admin@supersoft
#server.ssl.keyStoreType: PKCS12
#server.ssl.keyAlias: payco2
#server.port=8081
logging.level.org.apache.tomcat=DEBUG
logging.level.org.apache.catalina=DEBUG

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/transgatepay_db
#spring.datasource.username=root
#spring.datasource.password

spring.datasource.url=jdbc:mysql://10.13.3.4:3306/transgateweb_db
spring.datasource.username=sparkpayweb
spring.datasource.password=Admin12+

#spring.datasource.url=jdbc:mysql://10.83.1.10:3306/transgateweb_db
#spring.datasource.username=root
#spring.datasource.password=passpass